# RealmsCore by Kyle Necrowolf
# Configuration

# Thank you for using RealmsCore! See the other Realms plugins at http://wolfiamc.com/plugins

# RealmsCore help can be found at http://wolfiamc.com/plugins/realmscore
# Please read the Getting Started section, as it explains possible conflicts with other plugins. 
# Most servers won't need to modify this config, so if you're not sure what to change, just try out the default settings. 

# Don't change the formatting of this file, or Bukkit will complain. To reset this config to default, just delete it. 
# We recommend using VS Code (https://code.visualstudio.com/) to modify this file, as it will help you with formatting.
# Do NOT use tabs (tab indent) - use spaces. VS Code will automatically insert spaces, but other text editors won't.

# Most options can be applied with "/realmscore reload". Some options (marked below) require a server restart to take effect.
# However, you are encouraged to restart your server after ALL changes to keep your server running smoothly.


general:

  # Whether /list should show all players. If false, only admins are listed. Default true.
  list-all-players: true

  # Whether a list of online admins should be shown on login. Default true.
  show-admins-on-join: true

  # Whether a MOTD (message-of-the-day) prompt should be shown on login. Default true.
  # Edit the prompt in RealmsCore/prompts/motd.yml
  show-motd-on-join: true

  # Whether commands that accept player names should also accept display names (nicknames). Default true.
  search-player-displaynames: true

  # Whether some commands that accept player names should also accept offline player names. Default true.
  search-offline-players: true



appearance:

  # Whether to display some messages in the actionbar, instead of cluttering the chat. Default true.
  use-actionbar-messages: true


  # The colours here are used for all text in all Realms plugins, so you can quickly re-theme your server.
  # You can use any of the Minecraft color technical names: https://minecraft.gamepedia.com/Formatting_codes#Color_codes
  colors:
    # The color of normal messages. Default GRAY.
    message: GRAY
    # The color of non-important information messages. Default DARK_GRAY.
    info: DARK_GRAY
    # The color of error messages. Default RED.
    error: RED
    # The color to identify admins. Used in the admin prefix and wherever the word Admins appears. Default DARK_PURPLE.
    admin: DARK_PURPLE
    # The color of join/quit messages. Default YELLOW.
    join-quit: YELLOW


  text:

    # The prefix for admin display names. We like the simple plus, but you can use anything. Default "+".
    admin-prefix: "+"
    # The word for admins. If you prefer to use the term "Overlord" instead of "Admin", set that here. Default "Admin".
    admin-name: "Admin"

    # The message when a player joins/leaves the server. Default "%s joined/left the game".
    join-message: "%s joined the game"
    quit-message: "%s left the game"
    # The message when a player joins the server for the first time. Default "Welcome to the server!".
    first-join-message: "Welcome to the server!"

    # The message when a player doesn't have permission to use a command. Default "You can't use this command! Ask an %s for help.".
    no-permission-message: "You can't use this command! Ask an %s for help."



# RealmsCore has a built-in permissions system. Read about it at http://wolfiamc.com/plugins/realmscore/permissions
permissions:

  # Whether the built-in permissions system is enabled. Default true.
  # NOTE: If you have another permissions plugin, set this to false. Otherwise, leave it as true. 
  # RESTART REQUIRED: After changing this, you must restart your server.
  enabled: true


  # The following three settings control the Admin Multi-Check security feature. This protects the use of permissions and moderation commands on your server.
  # Learn more at http://wolfiamc.com/plugins/realmscore/permissions/admin-multi-check/

  # Whether to check both the permission "realms.admin" and the playerperms.yml file to make sure players are admins. Default true.
  # You should not need to disable, unless you are seeing "failed security check (Admin Multi-Check failed)" for legitimate admins.
  # This option is automatically disabled if permissions are disabled above.
  multi-check-players: true

  # Whether the console is considered an admin. If true, permissions and moderation commands can be used from the console. Default true.
  allow-console-admin-commands: true

  # Whether command blocks are considered admins. If true, permissions and moderation commands can be used from command blocks. Default false.
  # Do not enable unless needed, as this allows commands to be run without restrictions, and any player on your server can maliciously activate command blocks.
  allow-command-block-admin-commands: false

  # Whether the remote console (RCON) is considered an admin. If true, permissions and moderation commands can be used from RCON. Default false.
  # Do not enable unless needed, as it could open your server up to remote attackers. 
  allow-rcon-admin-commands: false


  # Whether players are "locked out" when logging in from an unrecognized IP. Default false.
  # Locked out players can only use their default permission set. Other sets are not available, until an admin approves it.
  # This option has no effect if permissions are disabled above.
  lockout-unrecognized-ips: false



players:

  # Whether RealmsCore will manage chat formatting. Default true.
  # NOTE: If you want to use another plugin for chat formatting or display names, set this to false.
  # Setting this to false will disable RealmsCore displaynames, titles and realms in chat, as well as join/quit messages. Most of the options under "text" above will be ignored.
  use-chat-formatting: true


  # Whether players can be marked AFK (away from keyboard). Default true.
  # When true, players can set their status to AFK with "/afk [optional message...]", or automatically after the time set below.
  # RESTART REQUIRED: After changing this, you must restart your server.
  afk-enabled: true

  # How many seconds before players are marked AFK, if they do not move, chat, or run commands. Default 180 seconds (3 minutes).
  # Set this to 0 to only mark players AFK when they use the command. 
  # RESTART REQUIRED: If changing to/from 0, you must restart your server.
  time-before-afk: 180



realms:

  # Where to load realms from. Default "playerdata".
  # You can import realms from other plugins (such as Factions). See here for instructions: http://wolfiamc.com/plugins/realmscore/realms/import-other-plugins/
  load-realms-from: "playerdata"


  # Whether to integrate with Minecraft Scoreboards. Default true.
  # When true, players are automatically added to a scoreboard team for their realm.
  use-minecraft-scoreboard: true

  scoreboard-options:
    # Whether to block friendly-fire between players in the same realm. Default false.
    # Requires use-minecraft-scoreboard to be true.
    block-friendly-fire: false

    # Whether realm members can see each other when invisible. Default false.
    # Requires use-minecraft-scoreboard to be true.
    see-friendly-invisibles: false

    # Whether nametags are visible to other players. Default "always".
    # Can be "always", "hideForOwnTeam" (nametags are hidden for players in same realm), "hideForOtherTeams" (nametags hidden for players in different realms), or "never" (always hide nametags for players in realms).
    name-tag-visibility: "always"

    # Whether death messages are visible to other players. Default "always".
    # Can be "always", "hideForOwnTeam" (messages are hidden for players in same realm), "hideForOtherTeams" (messages hidden for players in different realms), or "never" (always hide messages for players in realms).
    death-message-visibility: "always"

    # Whether players collide (push/move other players) with each other. Default "always".
    # Can be "always", "pushOwnTeam" (players only collide if in same realm), "pushOtherTeams" (players only collide if in different realms), or "never" (players in realms never collide).
    collision-rule: "always"


  # How many players are needed to start a new realm. Default 1 player.
  # 1 means any player can start a realm by themselves. Higher values require other players to join them, before the realm is created.
  # Set to 0 to block players from creating realms altogether.
  players-for-new-realm: 1

  # Whether players can create realms, if not currently part of one. Default true.
  # Setting this to false restricts players to creating sub-realms only. 
  players-create-new-realms: true

  # Whether only realm officers can create sub-realms. Default false.
  officers-create-sub-realms: false
